# Generated by Django 6.0.1 on 2026-01-12 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0003_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('Internship', 'Internship'), ('volunteer', 'Volunteer')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='job_pic/'),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('posted', 'Posted'), ('filled', 'Filled')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_add',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='practise.location'),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
