# Generated by Django 6.0.1 on 2026-01-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0004_location_remove_job_user_job_category_job_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='updated_add',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='job_pic/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('posted', 'Posted'), ('filled', 'Filled')], default='draft', max_length=20),
        ),
    ]
