# Generated by Django 6.0.1 on 2026-01-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practise', '0005_rename_updated_add_job_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='location',
        ),
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='job',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
